'''
-------------------------------------------------------------------------------
Name:	main.py
Purpose: a nba draft game that allows up to five players do an nba roster draft for different years based off choice. 

Author:	Adhvaryu.J

Created:	08/04/2021
-------------------------------------------------------------------------------
'''

print("")
print("")
print("**** WELCOME TO YOUR NBA FANTASY LEAGUE ****")
print("In this game you and your friends will be able to create NBA teams based off the players provided depending on the year you choose! Lets get started!")

print("")

participants = int(input("How Many People Are Playing (2-5 Players):"))
while participants >= 2 or participants <= 5: 
  if participants == 2:
    Player1 = str(input("Player 1: "))
    Player2 = str(input("Player 2: "))
    break
  elif participants == 3:
    Player1 = str(input("Player 1: "))
    Player2 = str(input("Player 2: "))
    Player3 = str(input("Player 3: "))
    break
  elif participants == 4:
    Player1 = str(input("Player 1: "))
    Player2 = str(input("Player 2: "))
    Player3 = str(input("Player 3: "))
    Player4 = str(input("Player 4: "))
    break
  elif participants == 5:
    Player1 = str(input("Player 1: "))
    Player2 = str(input("Player 2: "))
    Player3 = str(input("Player 3: "))
    Player4 = str(input("Player 4: "))
    Player5 = str(input("Player 5: "))
    break
  else:
    participants = int(input("How Many People Are Playing: (2-5 Players):"))
    continue

print("")
print("What Year Would You Like To Play In? a)2018/19 b)2011/12 c)1995/96:")
year = int(input(""))

D1995_1 = "Michael Jordan"
D1995_2 = "Hakeem Olajuwon"
D1995_3 = "Shaquille O'Neal"
D1995_4 = "Karl Malone"
D1995_5 = "David Robinson" 
D1995_6 = "Charles Barkley"
D1995_7 = "Alonzo Mourning" 
D1995_8 = "Patrick Ewing" 
D1995_9 = "Reggie Miller"
D1995_10 = "Scottie Pippen" 
D1995_11 = "Mitch Richmond" 
D1995_12 = "Dennis Rodman" 
D1995_13 = "John Stockton"
D1995_14 = "Gary Payton" 
D1995_15 = "Dikembe Mutombo" 
D1995_16 = "Glen Rice" 
D1995_17 = "Damon Stoudamire" 
D1995_18 = "Jason Kidd"
D1995_19 = "Shawn Kemp" 
D1995_20 = "Grant Hill"
D1995_21 = "Glen Robinsonlll"
D1995_22 = "Larry Johnson" 
D1995_23 = "Juwan Howard"
D1995_24 = "Isaiah Rider"
D1995_25 = "Jalen Rose"

if participants == 2 and year == 1995: 
  print("")
  print("Here Are Your Players: ")
  print (D1995_1)
  print(D1995_2)
  print(D1995_3)
  print(D1995_4)
  print(D1995_5)
  print(D1995_6)
  print(D1995_7)
  print(D1995_8)
  print(D1995_9)
  print(D1995_10)
  print("")
elif participants == 3 and year == 1995:
  print("")
  print("Here Are Your Players: ")
  print(D1995_1)
  print(D1995_2)
  print(D1995_3)
  print(D1995_4)
  print(D1995_5)
  print(D1995_6)
  print(D1995_7)
  print(D1995_8)
  print(D1995_9)
  print(D1995_10)
  print(D1995_11)
  print(D1995_12)
  print(D1995_13)
  print(D1995_14)
  print(D1995_15)
elif participants == 4 and year == 1995:
  print("")
  print("Here Are Your Players: ")
  print(D1995_1)
  print(D1995_2)
  print(D1995_3)
  print(D1995_4)
  print(D1995_5)
  print(D1995_6)
  print(D1995_7)
  print(D1995_8)
  print(D1995_9)
  print(D1995_10)
  print(D1995_11)
  print(D1995_12)
  print(D1995_13)
  print(D1995_14)
  print(D1995_15)
  print(D1995_16)
  print(D1995_17)
  print(D1995_18)
  print(D1995_19)
  print(D1995_20)
elif participants == 5 and year == 1995:
  print("")
  print("Here Are Your Players: ")
  print(D1995_1)
  print(D1995_2)
  print(D1995_3)
  print(D1995_5)
  print(D1995_6)
  print(D1995_7)
  print(D1995_8)
  print(D1995_9)
  print(D1995_10)
  print(D1995_11)
  print(D1995_12)
  print(D1995_13)
  print(D1995_14)
  print(D1995_15)
  print(D1995_16)
  print(D1995_17)
  print(D1995_18)
  print(D1995_20)
  print(D1995_21)
  print(D1995_22)
  print(D1995_23)
  print(D1995_24)
  print(D1995_25)
 
D2011_1 = "Kevin Durant"
D2011_2 = "Kobe Bryant"
D2011_3 = "Lebron James"
D2011_4 = "Kevin Love"
D2011_5 = "Russell Westbrook" 
D2011_6 = "Dwayne Wade"
D2011_7 = "Carmelo Anthony" 
D2011_8 = "Lamarcus Aldrige" 
D2011_9 = "Dirk Nowitzki"
D2011_10 = "Chris Paul" 
D2011_11 = "Paul Pierce" 
D2011_12 = "Blake Griffin" 
D2011_13 = "Deron Williams"
D2011_14 = "Monta Ellis" 
D2011_15 = "Al Jefferson" 
D2011_16 = "Brandon Jennings" 
D2011_17 = "Rudy Gay" 
D2011_18 = "Danny Granger"
D2011_19 = "Tony Parker" 
D2011_20 = "Demarcus Cousins"
D2011_21 = "Chris Bosh"
D2011_22 = "Joe Johnson" 
D2011_23 = "James Harden"
D2011_24 = "Demar Derozan"
D2011_25 = "Pau Gasol"

if participants == 2 and year == 2011: 
  print("")
  print("Here Are Your Players: ")
  print (D2011_1)
  print(D2011_2)
  print(D2011_3)
  print(D2011_4)
  print(D2011_5)
  print(D2011_6)
  print(D2011_7)
  print(D2011_8)
  print(D2011_9)
  print(D2011_10)
elif participants == 3 and year == 2011:
  print("")
  print("Here Are Your Players: ")
  print(D2011_1)
  print(D2011_2)
  print(D2011_3)
  print(D2011_4)
  print(D2011_5)
  print(D2011_6)
  print(D2011_7)
  print(D2011_8)
  print(D2011_9)
  print(D2011_10)
  print(D2011_11)
  print(D2011_12)
  print(D2011_13)
  print(D2011_14)
  print(D2011_15)
elif participants == 4 and year == 2011:
  print("")
  print("Here Are Your Players: ")
  print(D2011_1)
  print(D2011_2)
  print(D2011_3)
  print(D2011_4)
  print(D2011_5)
  print(D2011_6)
  print(D2011_7)
  print(D2011_8)
  print(D2011_9)
  print(D2011_10)
  print(D2011_11)
  print(D2011_12)
  print(D2011_13)
  print(D2011_14)
  print(D2011_15)
  print(D2011_16)
  print(D2011_17)
  print(D2011_18)
  print(D2011_19)
  print(D2011_20)
elif participants == 5 and year == 2011:
  print("")
  print("Here Are Your Players: ")
  print(D2011_1)
  print(D2011_2)
  print(D2011_3)
  print(D2011_5)
  print(D2011_6)
  print(D2011_7)
  print(D2011_8)
  print(D2011_9)
  print(D2011_10)
  print(D2011_11)
  print(D2011_12)
  print(D2011_13)
  print(D2011_14)
  print(D2011_15)
  print(D2011_16)
  print(D2011_17)
  print(D2011_18)
  print(D2011_20)
  print(D2011_21)
  print(D2011_22)
  print(D2011_23)
  print(D2011_24)
  print(D2011_25)

D2018_1 = "Giannis Antentekumpo"
D2018_2 = "Kawhi Leonard"
D2018_3 = "Kevin Durant"
D2018_4 = "James Harden"
D2018_5 = "Paul George" 
D2018_6 = "Joel Embid"
D2018_7 = "Steph Curry" 
D2018_8 = "Devin Booker" 
D2018_9 = "Damian Lillard"
D2018_10 = "Kyrie Irving" 
D2018_11 = "Pascal Siakam" 
D2018_12 = "Kemba Walker" 
D2018_13 = "Bradley Beal"
D2018_14 = "Blake Griffin" 
D2018_15 = "Karl Anthony Towns" 
D2018_16 = "Donavan Mitchell" 
D2018_17 = "Russell Westbrook" 
D2018_18 = "Klay Thompson"
D2018_19 = "LuKa Doncic" 
D2018_20 = "Nikola Jokic"
D2018_21 = "Trae Young"
D2018_22 = "Andre Drummond" 
D2018_23 = "Jamal Murray"
D2018_24 = "Lamarcus Aldrige"
D2018_25 = "Julius Randle"

if participants == 2 and year == 2018: 
  print("")
  print("Here Are Your Players: ")
  print(D2018_1)
  print(D2018_2)
  print(D2018_3)
  print(D2018_4)
  print(D2018_5)
  print(D2018_6)
  print(D2018_7)
  print(D2018_8)
  print(D2018_9)
  print(D2018_10)
elif participants == 3 and year == 2018:
  print("")
  print("Here Are Your Players: ")
  print(D2018_1)
  print(D2018_2)
  print(D2018_3)
  print(D2018_4)
  print(D2018_5)
  print(D2018_6)
  print(D2018_7)
  print(D2018_8)
  print(D2018_9)
  print(D2018_10)
  print(D2018_11)
  print(D2018_12)
  print(D2018_13)
  print(D2018_14)
  print(D2018_15)
elif participants == 4 and year == 2018:
  print("")
  print("Here Are Your Players: ")
  print(D2018_1)
  print(D2018_2)
  print(D2018_3)
  print(D2018_4)
  print(D2018_5)
  print(D2018_6)
  print(D2018_7)
  print(D2018_8)
  print(D2018_9)
  print(D2018_10)
  print(D2018_11)
  print(D2018_12)
  print(D2018_13)
  print(D2018_14)
  print(D2018_15)
  print(D2018_16)
  print(D2018_17)
  print(D2018_18)
  print(D2018_19)
  print(D2018_20) 
elif participants == 5 and year == 2018:
  print("")
  print("Here Are Your Players: ")
  print(D2018_1)
  print(D2018_2)
  print(D2018_3)
  print(D2018_5)
  print(D2018_6)
  print(D2018_7)
  print(D2018_8)
  print(D2018_9)
  print(D2018_10)
  print(D2018_11)
  print(D2018_12)
  print(D2018_13)
  print(D2018_14)
  print(D2018_15)
  print(D2018_16)
  print(D2018_17)
  print(D2018_18)
  print(D2018_20)
  print(D2018_21)
  print(D2018_22)
  print(D2018_23)
  print(D2018_24)
  print(D2018_25)
  print("")

if participants == 2 and year == 1995:
  print("")
  player1_firstpick = input(Player1 + " Choose Your First Pick: ")
  player2_firstpick = input(Player2 + " Choose Your First Pick: ")
  player2_secondpick = input(Player2 + " Choose Your Second Pick: ")
  player1_secondpick = input(Player1 + " Choose Your Second Pick: ")
  player2_thirdpick = input(Player2 + " Choose Your Third Pick: ")
  player1_thirdpick = input(Player1 + " Choose Your Third Pick: ")
  player2_fourthpick = input(Player2 + " Choose Your Fourth Pick: ")
  player1_fourthpick = input(Player1 + " Choose Your Fourth Pick: ")
  player2_fifthpick = input(Player2 + " Choose Your Fifth Pick: ")
  player1_fifthpick = input(Player1 + " Choose Your Fifth Pick: ")
elif participants == 3 and year == 1995:
  print("")
  player1_firstpick = input(Player1 + " Choose Your First Pick: ")
  player2_firstpick = input(Player2 + " Choose Your First Pick: ")
  player3_firstpick = input(Player3 + " Choose Your First Pick: ")
  player3_secondpick = input(Player3 + " Choose Your Second Pick: ")
  player2_secondpick = input(Player2 + " Choose Your Second Pick: ")
  player1_secondpick = input(Player1 + " Choose Your Second Pick: ")
  player2_thirdpick = input(Player2 + " Choose Your Third Pick: ")
  player3_thirdpick = input(Player3 + " Choose Your Third Pick: ")
  player1_thirdpick = input(Player1 + " Choose Your Third Pick: ")
  player2_fourthpick = input(Player2 + " Choose Your Fourth Pick: ")
  player3_fourthpick = input(Player3 + " Choose Your Fourth Pick: ")
  player1_fourthpick = input(Player1 + " Choose Your Fourth Pick: ")
  player2_fifthpick = input(Player2 + " Choose Your Fifth Pick: ")
  player3_fifthpick = input(Player3 + " Choose Your Fifth Pick: ")
  player1_fifthpick = input(Player1 + " Choose Your Fifth Pick: ")
elif participants == 4 and year == 1995:
  print("")
  player1_firstpick = input(Player1 + " Choose Your First Pick: ")
  player2_firstpick = input(Player2 + " Choose Your First Pick: ")
  player3_firstpick = input(Player3 + " Choose Your First Pick: ")
  player4_firstpick = input(Player4 + " Choose Your First Pick: ")
  player4_secondpick = input(Player4 + " Choose Your Second Pick: ")
  player3_secondpick = input(Player3 + " Choose Your Second Pick: ")
  player2_secondpick = input(Player2 + " Choose Your Second Pick: ")
  player1_secondpick = input(Player1 + " Choose Your Second Pick: ")
  player2_thirdpick = input(Player2 + " Choose Your Third Pick: ")
  player3_thirdpick = input(Player3 + " Choose Your Third Pick: ")
  player4_thirdpick = input(Player4 + " Choose Your Third Pick: ")
  player1_thirdpick = input(Player1 + " Choose Your Third Pick: ")
  player2_fourthpick = input(Player2 + " Choose Your Fourth Pick: ")
  player3_fourthpick = input(Player3 + " Choose Your Fourth Pick: ")
  player4_fourthpick = input(Player4 + " Choose Your Fourth Pick: ")
  player1_fourthpick = input(Player1 + " Choose Your Fourth Pick: ")
  player2_fifthpick = input(Player2 + " Choose Your Fifth Pick: ")
  player3_fifthpick = input(Player3 + " Choose Your Fifth Pick: ")
  player4_fifthpick = input(Player4 + " Choose Your Fifth Pick: ")
  player1_fifthpick = input(Player1 + " Choose Your Fifth Pick: ")
elif participants == 5 and year == 1995:
  print("")
  player1_firstpick = input(Player1 + " Choose Your First Pick: ")
  player2_firstpick = input(Player2 + " Choose Your First Pick: ")
  player3_firstpick = input(Player3 + " Choose Your First Pick: ")
  player4_firstpick = input(Player4 + " Choose Your First Pick: ")
  player5_firstpick = input(Player5 + " Choose Your First Pick: ")
  player5_secondpick = input(Player5 + " Choose Your Second Pick: ")
  player4_secondpick = input(Player4 + " Choose Your Second Pick: ")
  player3_secondpick = input(Player3 + " Choose Your Second Pick: ")
  player2_secondpick = input(Player2 + " Choose Your Second Pick: ")
  player1_secondpick = input(Player1 + " Choose Your Second Pick: ")
  player2_thirdpick = input(Player2 + " Choose Your Third Pick: ")
  player3_thirdpick = input(Player3 + " Choose Your Third Pick: ")
  player4_thirdpick = input(Player4 + " Choose Your Third Pick: ")
  player5_thirdpick = input(Player5 + " Choose Your Third Pick: ")
  player1_thirdpick = input(Player1 + " Choose Your Third Pick: ")
  player2_fourthpick = input(Player2 + " Choose Your Fourth Pick: ")
  player3_fourthpick = input(Player3 + " Choose Your Fourth Pick: ")
  player4_fourthpick = input(Player4 + " Choose Your Fourth Pick: ")
  player5_fourthpick = input(Player5 + " Choose Your Fourth Pick: ")
  player1_fourthpick = input(Player1 + " Choose Your Fourth Pick: ")
  player2_fifthpick = input(Player2 + " Choose Your Fifth Pick: ")
  player3_fifthpick = input(Player3 + " Choose Your Fifth Pick: ")
  player4_fifthpick = input(Player4 + " Choose Your Fifth Pick: ")
  player5_fifthpick = input(Player5 + " Choose Your Fifth Pick: ")
  player1_fifthpick = input(Player1 + " Choose Your Fifth Pick: ")

if participants == 2 and year == 2011:
  print("")
  player1_firstpick = input(Player1 + " Choose Your First Pick: ")
  player2_firstpick = input(Player2 + " Choose Your First Pick: ")
  player2_secondpick = input(Player2 + " Choose Your Second Pick: ")
  player1_secondpick = input(Player1 + " Choose Your Second Pick: ")
  player2_thirdpick = input(Player2 + " Choose Your Third Pick: ")
  player1_thirdpick = input(Player1 + " Choose Your Third Pick: ")
  player2_fourthpick = input(Player2 + " Choose Your Fourth Pick: ")
  player1_fourthpick = input(Player1 + " Choose Your Fourth Pick: ")
  player2_fifthpick = input(Player2 + " Choose Your Fifth Pick: ")
  player1_fifthpick = input(Player1 + " Choose Your Fifth Pick: ")
elif participants == 3 and year == 2011:
  print("")
  player1_firstpick = input(Player1 + " Choose Your First Pick: ")
  player2_firstpick = input(Player2 + " Choose Your First Pick: ")
  player3_firstpick = input(Player3 + " Choose Your First Pick: ")
  player3_secondpick = input(Player3 + " Choose Your Second Pick: ")
  player2_secondpick = input(Player2 + " Choose Your Second Pick: ")
  player1_secondpick = input(Player1 + " Choose Your Second Pick: ")
  player2_thirdpick = input(Player2 + " Choose Your Third Pick: ")
  player3_thirdpick = input(Player3 + " Choose Your Third Pick: ")
  player1_thirdpick = input(Player1 + " Choose Your Third Pick: ")
  player2_fourthpick = input(Player2 + " Choose Your Fourth Pick: ")
  player3_fourthpick = input(Player3 + " Choose Your Fourth Pick: ")
  player1_fourthpick = input(Player1 + " Choose Your Fourth Pick: ")
  player2_fifthpick = input(Player2 + " Choose Your Fifth Pick: ")
  player3_fifthpick = input(Player3 + " Choose Your Fifth Pick: ")
  player1_fifthpick = input(Player1 + " Choose Your Fifth Pick: ")
elif participants == 4 and year == 2011:
  print("")
  player1_firstpick = input(Player1 + " Choose Your First Pick: ")
  player2_firstpick = input(Player2 + " Choose Your First Pick: ")
  player3_firstpick = input(Player3 + " Choose Your First Pick: ")
  player4_firstpick = input(Player4 + " Choose Your First Pick: ")
  player4_secondpick = input(Player4 + " Choose Your Second Pick: ")
  player3_secondpick = input(Player3 + " Choose Your Second Pick: ")
  player2_secondpick = input(Player2 + " Choose Your Second Pick: ")
  player1_secondpick = input(Player1 + " Choose Your Second Pick: ")
  player2_thirdpick = input(Player2 + " Choose Your Third Pick: ")
  player3_thirdpick = input(Player3 + " Choose Your Third Pick: ")
  player4_thirdpick = input(Player4 + " Choose Your Third Pick: ")
  player1_thirdpick = input(Player1 + " Choose Your Third Pick: ")
  player2_fourthpick = input(Player2 + " Choose Your Fourth Pick: ")
  player3_fourthpick = input(Player3 + " Choose Your Fourth Pick: ")
  player4_fourthpick = input(Player4 + " Choose Your Fourth Pick: ")
  player1_fourthpick = input(Player1 + " Choose Your Fourth Pick: ")
  player2_fifthpick = input(Player2 + " Choose Your Fifth Pick: ")
  player3_fifthpick = input(Player3 + " Choose Your Fifth Pick: ")
  player4_fifthpick = input(Player4 + " Choose Your Fifth Pick: ")
  player1_fifthpick = input(Player1 + " Choose Your Fifth Pick: ")
elif participants == 5 and year == 2011:
  print("")
  player1_firstpick = input(Player1 + " Choose Your First Pick: ")
  player2_firstpick = input(Player2 + " Choose Your First Pick: ")
  player3_firstpick = input(Player3 + " Choose Your First Pick: ")
  player4_firstpick = input(Player4 + " Choose Your First Pick: ")
  player5_firstpick = input(Player5 + " Choose Your First Pick: ")
  player5_secondpick = input(Player5 + " Choose Your Second Pick: ")
  player4_secondpick = input(Player4 + " Choose Your Second Pick: ")
  player3_secondpick = input(Player3 + " Choose Your Second Pick: ")
  player2_secondpick = input(Player2 + " Choose Your Second Pick: ")
  player1_secondpick = input(Player1 + " Choose Your Second Pick: ")
  player2_thirdpick = input(Player2 + " Choose Your Third Pick: ")
  player3_thirdpick = input(Player3 + " Choose Your Third Pick: ")
  player4_thirdpick = input(Player4 + " Choose Your Third Pick: ")
  player5_thirdpick = input(Player5 + " Choose Your Third Pick: ")
  player1_thirdpick = input(Player1 + " Choose Your Third Pick: ")
  player2_fourthpick = input(Player2 + " Choose Your Fourth Pick: ")
  player3_fourthpick = input(Player3 + " Choose Your Fourth Pick: ")
  player4_fourthpick = input(Player4 + " Choose Your Fourth Pick: ")
  player5_fourthpick = input(Player5 + " Choose Your Fourth Pick: ")
  player1_fourthpick = input(Player1 + " Choose Your Fourth Pick: ")
  player2_fifthpick = input(Player2 + " Choose Your Fifth Pick: ")
  player3_fifthpick = input(Player3 + " Choose Your Fifth Pick: ")
  player4_fifthpick = input(Player4 + " Choose Your Fifth Pick: ")
  player5_fifthpick = input(Player5 + " Choose Your Fifth Pick: ")
  player1_fifthpick = input(Player1 + " Choose Your Fifth Pick: ")

if participants == 2 and year == 2018:
  print("")
  player1_firstpick = input(Player1 + " Choose Your First Pick: ")
  player2_firstpick = input(Player2 + " Choose Your First Pick: ")
  player2_secondpick = input(Player2 + " Choose Your Second Pick: ")
  player1_secondpick = input(Player1 + " Choose Your Second Pick: ")
  player2_thirdpick = input(Player2 + " Choose Your Third Pick: ")
  player1_thirdpick = input(Player1 + " Choose Your Third Pick: ")
  player2_fourthpick = input(Player2 + " Choose Your Fourth Pick: ")
  player1_fourthpick = input(Player1 + " Choose Your Fourth Pick: ")
  player2_fifthpick = input(Player2 + " Choose Your Fifth Pick: ")
  player1_fifthpick = input(Player1 + " Choose Your Fifth Pick: ")
elif participants == 3 and year == 2018:
  print("")
  player1_firstpick = input(Player1 + " Choose Your First Pick: ")
  player2_firstpick = input(Player2 + " Choose Your First Pick: ")
  player3_firstpick = input(Player3 + " Choose Your First Pick: ")
  player3_secondpick = input(Player3 + " Choose Your Second Pick: ")
  player2_secondpick = input(Player2 + " Choose Your Second Pick: ")
  player1_secondpick = input(Player1 + " Choose Your Second Pick: ")
  player2_thirdpick = input(Player2 + " Choose Your Third Pick: ")
  player3_thirdpick = input(Player3 + " Choose Your Third Pick: ")
  player1_thirdpick = input(Player1 + " Choose Your Third Pick: ")
  player2_fourthpick = input(Player2 + " Choose Your Fourth Pick: ")
  player3_fourthpick = input(Player3 + " Choose Your Fourth Pick: ")
  player1_fourthpick = input(Player1 + " Choose Your Fourth Pick: ")
  player2_fifthpick = input(Player2 + " Choose Your Fifth Pick: ")
  player3_fifthpick = input(Player3 + " Choose Your Fifth Pick: ")
  player1_fifthpick = input(Player1 + " Choose Your Fifth Pick: ")
elif participants == 4 and year == 2018:
  print("")
  player1_firstpick = input(Player1 + " Choose Your First Pick: ")
  player2_firstpick = input(Player2 + " Choose Your First Pick: ")
  player3_firstpick = input(Player3 + " Choose Your First Pick: ")
  player4_firstpick = input(Player4 + " Choose Your First Pick: ")
  player4_secondpick = input(Player4 + " Choose Your Second Pick: ")
  player3_secondpick = input(Player3 + " Choose Your Second Pick: ")
  player2_secondpick = input(Player2 + " Choose Your Second Pick: ")
  player1_secondpick = input(Player1 + " Choose Your Second Pick: ")
  player2_thirdpick = input(Player2 + " Choose Your Third Pick: ")
  player3_thirdpick = input(Player3 + " Choose Your Third Pick: ")
  player4_thirdpick = input(Player4 + " Choose Your Third Pick: ")
  player1_thirdpick = input(Player1 + " Choose Your Third Pick: ")
  player2_fourthpick = input(Player2 + " Choose Your Fourth Pick: ")
  player3_fourthpick = input(Player3 + " Choose Your Fourth Pick: ")
  player4_fourthpick = input(Player4 + " Choose Your Fourth Pick: ")
  player1_fourthpick = input(Player1 + " Choose Your Fourth Pick: ")
  player2_fifthpick = input(Player2 + " Choose Your Fifth Pick: ")
  player3_fifthpick = input(Player3 + " Choose Your Fifth Pick: ")
  player4_fifthpick = input(Player4 + " Choose Your Fifth Pick: ")
  player1_fifthpick = input(Player1 + " Choose Your Fifth Pick: ")
elif participants == 5 and year == 2018:
  print("")
  player1_firstpick = input(Player1 + " Choose Your First Pick: ")
  player2_firstpick = input(Player2 + " Choose Your First Pick: ")
  player3_firstpick = input(Player3 + " Choose Your First Pick: ")
  player4_firstpick = input(Player4 + " Choose Your First Pick: ")
  player5_firstpick = input(Player5 + " Choose Your First Pick: ")
  player5_secondpick = input(Player5 + " Choose Your Second Pick: ")
  player4_secondpick = input(Player4 + " Choose Your Second Pick: ")
  player3_secondpick = input(Player3 + " Choose Your Second Pick: ")
  player2_secondpick = input(Player2 + " Choose Your Second Pick: ")
  player1_secondpick = input(Player1 + " Choose Your Second Pick: ")
  player2_thirdpick = input(Player2 + " Choose Your Third Pick: ")
  player3_thirdpick = input(Player3 + " Choose Your Third Pick: ")
  player4_thirdpick = input(Player4 + " Choose Your Third Pick: ")
  player5_thirdpick = input(Player5 + " Choose Your Third Pick: ")
  player1_thirdpick = input(Player1 + " Choose Your Third Pick: ")
  player2_fourthpick = input(Player2 + " Choose Your Fourth Pick: ")
  player3_fourthpick = input(Player3 + " Choose Your Fourth Pick: ")
  player4_fourthpick = input(Player4 + " Choose Your Fourth Pick: ")
  player5_fourthpick = input(Player5 + " Choose Your Fourth Pick: ")
  player1_fourthpick = input(Player1 + " Choose Your Fourth Pick: ")
  player2_fifthpick = input(Player2 + " Choose Your Fifth Pick: ")
  player3_fifthpick = input(Player3 + " Choose Your Fifth Pick: ")
  player4_fifthpick = input(Player4 + " Choose Your Fifth Pick: ")
  player5_fifthpick = input(Player5 + " Choose Your Fifth Pick: ")
  player1_fifthpick = input(Player1 + " Choose Your Fifth Pick: ")

if participants == 2 and year == 1995:
  print("")
  print("The Draft Is Finished, Here Are The Rosters: ")
  print("")
  print(Player1 + ("'s team is..."))
  print("")
  print(player1_firstpick)
  print(player1_secondpick)
  print(player1_thirdpick)
  print(player1_fourthpick)
  print(player1_fifthpick)
  print("")
  print(Player2 + ("'s team is..."))
  print("")
  print(player2_firstpick)
  print(player2_secondpick)
  print(player2_thirdpick)
  print(player2_fourthpick)
  print(player2_fifthpick)
elif participants == 3 and year == 1995:
  print("")
  print("The Draft Is Finished, Here Are The Rosters: ")
  print("")
  print(Player1 + ("'s team is..."))
  print("")
  print(player1_firstpick)
  print(player1_secondpick)
  print(player1_thirdpick)
  print(player1_fourthpick)
  print(player1_fifthpick)
  print("")
  print(Player2 + ("'s team is..."))
  print("")
  print(player2_firstpick)
  print(player2_secondpick)
  print(player2_thirdpick)
  print(player2_fourthpick)
  print(player2_fifthpick)
  print("")
  print(Player3 + ("'s team is..."))
  print("")
  print(player3_firstpick)
  print(player3_secondpick)
  print(player3_thirdpick)
  print(player3_fourthpick)
  print(player3_fifthpick)
elif participants == 4 and year == 1995:
  print("")
  print("The Draft Is Finished, Here Are The Rosters: ")
  print("")
  print(Player1 + ("'s team is..."))
  print("")
  print(player1_firstpick)
  print(player1_secondpick)
  print(player1_thirdpick)
  print(player1_fourthpick)
  print(player1_fifthpick)
  print("")
  print(Player2 + ("'s team is..."))
  print("")
  print(player2_firstpick)
  print(player2_secondpick)
  print(player2_thirdpick)
  print(player2_fourthpick)
  print(player2_fifthpick)
  print("")
  print(Player3 + ("'s team is..."))
  print("")
  print(player3_firstpick)
  print(player3_secondpick)
  print(player3_thirdpick)
  print(player3_fourthpick)
  print(player3_fifthpick)
  print("")
  print(Player4 + ("'s team is..."))
  print("")
  print(player4_firstpick)
  print(player4_secondpick)
  print(player4_thirdpick)
  print(player4_fourthpick)
  print(player4_fifthpick)
elif participants == 5 and year == 1995:
  print("")
  print("The Draft Is Finished, Here Are The Rosters: ")
  print("")
  print(Player1 + ("'s team is..."))
  print("")
  print(player1_firstpick)
  print(player1_secondpick)
  print(player1_thirdpick)
  print(player1_fourthpick)
  print(player1_fifthpick)
  print("")
  print(Player2 + ("'s team is..."))
  print("")
  print(player2_firstpick)
  print(player2_secondpick)
  print(player2_thirdpick)
  print(player2_fourthpick)
  print(player2_fifthpick)
  print("")
  print(Player3 + ("'s team is..."))
  print("")
  print(player3_firstpick)
  print(player3_secondpick)
  print(player3_thirdpick)
  print(player3_fourthpick)
  print(player3_fifthpick)
  print("")
  print(Player4 + ("'s team is..."))
  print("")
  print(player4_firstpick)
  print(player4_secondpick)
  print(player4_thirdpick)
  print(player4_fourthpick)
  print(player4_fifthpick)
  print("")
  print(Player5 + ("'s team is..."))
  print("")
  print(player5_firstpick)
  print(player5_secondpick)
  print(player5_thirdpick)
  print(player5_fourthpick)
  print(player5_fifthpick)

if participants == 2 and year == 2011:
  print("")
  print("The Draft Is Finished, Here Are The Rosters: ")
  print("")
  print(Player1 + ("'s team is..."))
  print("")
  print(player1_firstpick)
  print(player1_secondpick)
  print(player1_thirdpick)
  print(player1_fourthpick)
  print(player1_fifthpick)
  print("")
  print(Player2 + ("'s team is..."))
  print("")
  print(player2_firstpick)
  print(player2_secondpick)
  print(player2_thirdpick)
  print(player2_fourthpick)
  print(player2_fifthpick)
elif participants == 3 and year == 2011:
  print("")
  print("The Draft Is Finished, Here Are The Rosters: ")
  print("")
  print(Player1 + ("'s team is..."))
  print("")
  print(player1_firstpick)
  print(player1_secondpick)
  print(player1_thirdpick)
  print(player1_fourthpick)
  print(player1_fifthpick)
  print("")
  print(Player2 + ("'s team is..."))
  print("")
  print(player2_firstpick)
  print(player2_secondpick)
  print(player2_thirdpick)
  print(player2_fourthpick)
  print(player2_fifthpick)
  print("")
  print(Player3 + ("'s team is..."))
  print("")
  print(player3_firstpick)
  print(player3_secondpick)
  print(player3_thirdpick)
  print(player3_fourthpick)
  print(player3_fifthpick)
elif participants == 4 and year == 2011:
  print("")
  print("The Draft Is Finished, Here Are The Rosters: ")
  print("")
  print(Player1 + ("'s team is..."))
  print("")
  print(player1_firstpick)
  print(player1_secondpick)
  print(player1_thirdpick)
  print(player1_fourthpick)
  print(player1_fifthpick)
  print("")
  print(Player2 + ("'s team is..."))
  print("")
  print(player2_firstpick)
  print(player2_secondpick)
  print(player2_thirdpick)
  print(player2_fourthpick)
  print(player2_fifthpick)
  print("")
  print(Player3 + ("'s team is..."))
  print("")
  print(player3_firstpick)
  print(player3_secondpick)
  print(player3_thirdpick)
  print(player3_fourthpick)
  print(player3_fifthpick)
  print("")
  print(Player4 + ("'s team is..."))
  print("")
  print(player4_firstpick)
  print(player4_secondpick)
  print(player4_thirdpick)
  print(player4_fourthpick)
  print(player4_fifthpick)
elif participants == 5 and year == 2011:
  print("")
  print("The Draft Is Finished, Here Are The Rosters: ")
  print("")
  print(Player1 + ("'s team is..."))
  print("")
  print(player1_firstpick)
  print(player1_secondpick)
  print(player1_thirdpick)
  print(player1_fourthpick)
  print(player1_fifthpick)
  print("")
  print(Player2 + ("'s team is..."))
  print("")
  print(player2_firstpick)
  print(player2_secondpick)
  print(player2_thirdpick)
  print(player2_fourthpick)
  print(player2_fifthpick)
  print("")
  print(Player3 + ("'s team is..."))
  print("")
  print(player3_firstpick)
  print(player3_secondpick)
  print(player3_thirdpick)
  print(player3_fourthpick)
  print(player3_fifthpick)
  print("")
  print(Player4 + ("'s team is..."))
  print("")
  print(player4_firstpick)
  print(player4_secondpick)
  print(player4_thirdpick)
  print(player4_fourthpick)
  print(player4_fifthpick)
  print("")
  print(Player5 + ("'s team is..."))
  print("")
  print(player5_firstpick)
  print(player5_secondpick)
  print(player5_thirdpick)
  print(player5_fourthpick)
  print(player5_fifthpick)

if participants == 2 and year == 2018:
  print("")
  print("The Draft Is Finished, Here Are The Rosters: ")
  print("")
  print(Player1 + ("'s team is..."))
  print("")
  print(player1_firstpick)
  print(player1_secondpick)
  print(player1_thirdpick)
  print(player1_fourthpick)
  print(player1_fifthpick)
  print("")
  print(Player2 + ("'s team is..."))
  print("")
  print(player2_firstpick)
  print(player2_secondpick)
  print(player2_thirdpick)
  print(player2_fourthpick)
  print(player2_fifthpick)
elif participants == 3 and year == 2018:
  print("")
  print("The Draft Is Finished, Here Are The Rosters: ")
  print("")
  print(Player1 + ("'s team is..."))
  print("")
  print(player1_firstpick)
  print(player1_secondpick)
  print(player1_thirdpick)
  print(player1_fourthpick)
  print(player1_fifthpick)
  print("")
  print(Player2 + ("'s team is..."))
  print("")
  print(player2_firstpick)
  print(player2_secondpick)
  print(player2_thirdpick)
  print(player2_fourthpick)
  print(player2_fifthpick)
  print("")
  print(Player3 + ("'s team is..."))
  print("")
  print(player3_firstpick)
  print(player3_secondpick)
  print(player3_thirdpick)
  print(player3_fourthpick)
  print(player3_fifthpick)
elif participants == 4 and year == 2018:
  print("")
  print("The Draft Is Finished, Here Are The Rosters: ")
  print("")
  print(Player1 + ("'s team is..."))
  print("")
  print(player1_firstpick)
  print(player1_secondpick)
  print(player1_thirdpick)
  print(player1_fourthpick)
  print(player1_fifthpick)
  print("")
  print(Player2 + ("'s team is..."))
  print("")
  print(player2_firstpick)
  print(player2_secondpick)
  print(player2_thirdpick)
  print(player2_fourthpick)
  print(player2_fifthpick)
  print("")
  print(Player3 + ("'s team is..."))
  print("")
  print(player3_firstpick)
  print(player3_secondpick)
  print(player3_thirdpick)
  print(player3_fourthpick)
  print(player3_fifthpick)
  print("")
  print(Player4 + ("'s team is..."))
  print("")
  print(player4_firstpick)
  print(player4_secondpick)
  print(player4_thirdpick)
  print(player4_fourthpick)
  print(player4_fifthpick)
elif participants == 5 and year == 2018:
  print("")
  print("The Draft Is Finished, Here Are The Rosters: ")
  print("")
  print(Player1 + ("'s team is..."))
  print("")
  print(player1_firstpick)
  print(player1_secondpick)
  print(player1_thirdpick)
  print(player1_fourthpick)
  print(player1_fifthpick)
  print("")
  print(Player2 + ("'s team is..."))
  print("")
  print(player2_firstpick)
  print(player2_secondpick)
  print(player2_thirdpick)
  print(player2_fourthpick)
  print(player2_fifthpick)
  print("")
  print(Player3 + ("'s team is..."))
  print("")
  print(player3_firstpick)
  print(player3_secondpick)
  print(player3_thirdpick)
  print(player3_fourthpick)
  print(player3_fifthpick)
  print("")
  print(Player4 + ("'s team is..."))
  print("")
  print(player4_firstpick)
  print(player4_secondpick)
  print(player4_thirdpick)
  print(player4_fourthpick)
  print(player4_fifthpick)
  print("")
  print(Player5 + ("'s team is..."))
  print("")
  print(player5_firstpick)
  print(player5_secondpick)
  print(player5_thirdpick)
  print(player5_fourthpick)
  print(player5_fifthpick)

print("")
print("In Order To Decide Who Wins, Group Together Three New Friends And Let Them Cast Their Votes Below:")

player1_votes = 0
player2_votes = 0
player3_votes = 0
player4_votes = 0
player5_votes = 0

for i in range(3):
  winner = input("")
  if winner == Player1:
    player1_votes = player1_votes + 1
  elif winner == Player2:
    player2_votes = player2_votes + 1
  elif winner == Player3:
    player3_votes = player3_votes + 1
  elif winner == Player4:
    player4_votes = player4_votes + 1
  elif winner == Player5:
    player5_votes = player5_votes + 1

print("")
if player1_votes == 2 or player1_votes == 3:
  print(Player1 + " Is The " + str(year) + " NBA Draft Winner!")
elif player2_votes == 2 or player2_votes == 3:
  print(Player2 + " Is The " + str(year) + " NBA Draft Winner!")
elif player3_votes == 2 or player3_votes == 3:
  print(Player3 + " Is The " + str(year) + " NBA Draft Winner!")
elif player4_votes == 2 or player4_votes == 3:
  print(Player4 + " Is The " + str(year) + " NBA Draft Winner!")
elif player5_votes == 2 or player5_votes == 3:
  print(Player5 + " Is The " + str(year) + " NBA Draft Winner!")